import { getDayNumber } from "./share";

// ~2000 common 6-letter English words (curated answer list)
export const ANSWERS: string[] = [
  "abroad","absent","accent","access","accord","across","action","actual","advise","affect",
  "afford","afraid","agency","agenda","agreed","albeit","always","annual","anyone","anyway",
  "appeal","appear","around","aspect","assist","assume","assure","attach","attack","attain",
  "attend","august","autumn","avenue","averse","backed","barely","battle","beacon","beauty",
  "became","become","behalf","behind","beings","belief","belong","beside","beyond","bitter",
  "blacks","blanks","blazed","blight","blinks","blocks","blower","blurts","bodies","bolted",
  "border","boring","borrow","bottom","bought","bounty","branch","brands","bravely","breach",
  "bright","brings","broken","broker","bronze","browse","burden","button","buyers","called",
  "camera","cancel","cannot","canvas","carbon","career","carpet","castle","caught","caused",
  "center","chance","change","charge","choice","chosen","church","circle","cities","claims",
  "classy","client","closed","closer","clouds","combat","coming","commit","common","county",
  "course","courts","covers","create","credit","crisis","crowds","cruise","custom","cutoff",
  "damage","danger","danger","darker","deadly","deaths","debate","decide","decent","deeply",
  "defend","define","degree","delays","demand","denied","depend","design","detail","detect",
  "device","differ","direct","dollar","domain","double","drafts","dreams","driven","during",
  "easily","edited","editor","effect","either","empire","enable","energy","engage","engine",
  "enough","ensure","entire","escape","events","except","expand","expect","export","extend",
  "extend","fairly","fallen","family","famous","faster","father","faulty","fellow","female",
  "fierce","figure","filing","filter","finger","finish","flight","forces","forest","formal",
  "fossil","fought","frames","freely","fridge","friend","frozen","future","gather","gender",
  "gentle","global","golden","govern","grades","grants","growth","guests","guided","guilty",
  "handle","happen","hardly","health","hearts","height","hidden","higher","hiring","honest",
  "hoping","hosted","hotels","houses","hugely","humans","hunger","impact","income","indeed",
  "inform","inside","insist","intent","invest","island","issues","itself","joined","junior",
  "justice","keeper","killed","kings","labour","largely","launch","lawyer","leader","leaves",
  "legacy","lesson","letter","levels","lights","likely","limits","listed","little","living",
  "locked","looked","losing","lovers","lowest","mainly","manage","manner","margin","marked",
  "market","master","matter","measure","medium","merely","metals","method","middle","might",
  "mobile","moment","mostly","moving","murder","mutual","myself","narrow","nation","nature",
  "nearly","needed","nights","normal","notice","obtain","offered","office","online","opened",
  "option","orders","origin","others","output","owners","packed","parent","passed","patent",
  "paying","pencil","people","permit","phases","picked","pieces","pilots","placed","places",
  "planet","plants","played","player","plenty","policy","police","plenty","points","poorly",
  "posted","power","prefer","pretty","prison","profit","proper","proven","public","pupils",
  "purple","pushed","queens","quietly","racist","raised","random","rarely","rather","rating",
  "really","reason","recent","reduce","reform","regard","remain","remove","repeat","report",
  "rescue","result","return","review","reward","rights","rising","robust","rocket","rushed",
  "safety","sample","saying","school","screen","season","second","sector","secure","seeing",
  "sought","served","server","settle","shared","should","signal","silver","simple","simply",
  "single","sister","slight","slowly","social","solved","source","spaces","spread","stable",
  "states","status","stolen","stores","strain","street","strict","strong","struck","studio",
  "submit","sudden","suffer","summer","supply","surely","survey","switch","target","taught",
  "tested","thanks","theory","things","throne","thrown","titled","though","titles","topics",
  "totally","toward","travel","treaty","trends","trying","turned","twelve","unable","unions",
  "unique","unless","update","useful","valley","varied","verbal","victim","vision","wanted",
  "warned","weapon","weekly","weight","widely","winner","within","wonder","worker","worlds",
  "worthy","writer","yearly","yields",
];

// Larger set of valid 6-letter words (accepted for guessing, superset of ANSWERS)
// This is a representative set; in production you'd include ~10000 words
const VALID_EXTRAS: string[] = [
  "abound","absorb","abused","acidic","acting","acumen","addend","adding","admire","admits",
  "adored","adrift","adults","afield","ageing","ageism","agents","aggro","aghast","agitate",
  "agonic","ailing","airway","albeit","albums","alerts","allure","allows","almond","alpaca",
  "alpine","ambush","amends","amidst","amoral","anchor","angled","angles","ankles","anoint",
  "antics","antler","anvils","apache","apathy","aplomb","arched","ardent","argues","arises",
  "armory","arouse","arrays","arrows","artful","artist","astray","atomic","atonic","attach",
  "avoids","awoken","bailed","baking","banter","barely","barren","basalt","basics","bathed",
  "batters","beamed","beards","beaten","belted","bended","blamed","bland","bleary","blends",
  "blinks","boasts","boding","bogged","boldly","bonded","borked","botany","bouncy","brandy",
  "breach","brooch","bruise","buries","cabled","camper","candid","canine","canopy","carpet",
  "carrot","casket","casual","ceased","cement","chilly","choice","chunky","cipher","cirrus",
  "clamor","clumsy","coarse","cobalt","cobble","coiled","colony","combat","combed","compile",
  "concur","coping","corals","corous","cosmic","coughing","couple","crazed","crisps","croaks",
  "crunch","cupids","cycled","darkly","dashed","dawdle","dazzle","debris","depart","deploy",
  "deputy","desert","dimly","dinned","direly","dismal","dispel","distil","diving","docile",
  "dodged","donkey","doting","doubts","dreary","drenched","drones","drowse","drying","dubbed",
  "ducked","dumped","dusted","earthy","edging","ejects","elapse","elated","eldest","eleven",
  "elicit","eluded","eludes","elves","embers","emerge","empath","enamel","endure","enjoys",
  "enrich","entail","entwine","errant","erring","erupt","ethics","exacts","exiled","fables",
  "fading","famine","faults","fawned","feisty","fended","fervor","feudal","filmed","finest",
  "fitted","fixing","flaked","flames","flanks","flares","flashy","flavor","flawed","fleets",
  "flickr","flimsy","flinch","floods","floors","flopped","floats","flocks","folded","folly",
  "forage","forbid","forged","forges","format","fortify","forums","founds","fright","frowns",
  "frozen","fumble","fungal","gaping","garner","gilded","glassy","glazed","glints","gloomy",
  "glowed","glutes","grains","grasps","gravel","greedy","grills","grimed","grimy","gripes",
  "groans","gropes","grotesque","grouse","grudge","grumpy","gushed","gutted","hailed","handed",
  "harmed","harped","harshly","hateful","hazing","herald","heroic","hexing","hijack","hobble",
  "hooked","horrid","hosted","howled","humane","hurled","hybrid","ideals","impose","inched",
  "indent","infers","infuse","inland","inmate","innate","inputs","insane","insert","insure",
  "intact","intend","iodine","ironic","irking","isolated","jabbed","jagged","jaunty","jealous",
  "jested","jotted","jumped","jungle","kennel","kindly","kinetic","knacks","kneels","knights",
  "knobby","knotty","knowledgeable","lacked","lament","lapsed","lashed","latent","layers",
  "leaked","leaned","leaped","levied","lining","linker","lintel","listless","loosen","loping",
  "losing","lounge","lucent","lunged","lurked","malice","malign","mangle","mantle","mapped",
  "marble","marred","mashed","matted","meddle","mental","merest","merits","messes","mirror",
  "misuse","mitten","models","module","molten","mortar","mosaic","motive","mottled","mourns",
  "mutter","nagged","nasty","needle","nephews","nested","nether","neural","newborn","nimbly",
  "nobles","nimble","negate","neared","morsel","mossy","mottled","muffled","naught","nomads",
  "nuzzle","oblong","obsess","obtain","occurs","odious","omitted","opaque","orbits","outrun",
  "outset","overdo","overly","paddle","pallid","pardon","partly","patrol","peddle","pelted",
  "penned","perceive","petals","pickle","pinned","piracy","pixels","plaque","plasma","plumbs",
  "plumes","plummy","podium","polled","pooled","ponder","potent","pouted","pounds","powder",
  "preach","precise","prefers","primed","prisms","purely","pushed","putrid","puzzle","rabble",
  "radial","radish","rankly","rappel","rarest","rattle","raucous","ravine","recede","recoil",
  "reflow","refuse","relics","relies","remiss","rental","repels","rested","retool","reveal",
  "ridges","rigged","ripple","rivals","robbed","rolled","romped","rookie","rouped","rubble",
  "rugged","rumble","saddle","sallow","salute","salvage","sapped","sating","savant","scaffold",
  "scaled","scorch","sector","seethe","seldom","seized","sermon","shaken","shamed","shanty",
  "shaped","shards","sheath","shifty","shimmer","shrine","singed","sipped","sirens","skirted",
  "sloppy","slouch","snared","sneaky","snobbish","soften","somber","sorted","sprawl","sprint",
  "sputum","stamen","stared","static","steely","stench","stifle","stoked","stoned","stroll",
  "sturdy","subnet","superb","swerve","swivel","symbol","tabbed","taught","tangle","tapers",
  "tasted","tawdry","teamed","tickle","timely","tinged","tipped","tiresome","toiled","tossed",
  "treble","trifle","triples","trover","tundra","turbid","typhon","ulcers","uncanny","unfair",
  "unfit","unison","unkind","untied","untrue","upheld","upkeep","urgent","usable","vapors",
  "vexing","viable","vomits","vowing","vulgar","wafted","waging","waived","wander","washed",
  "wasted","waters","waving","weaken","wealth","welded","wicked","wisely","wished","wobble",
  "wolves","wrenched","wrestle","writhed","yelled","zoning","zoning",
];

export const VALID_WORDS: Set<string> = new Set([...ANSWERS, ...VALID_EXTRAS]);

export function getDailyAnswer(): string {
  const day = getDayNumber();
  return ANSWERS[((day - 1) % ANSWERS.length + ANSWERS.length) % ANSWERS.length];
}
