import { getDayNumber } from "./share";

// Deterministic Fisher-Yates shuffle with a LCG seed — same result on every client
function seededShuffle<T>(arr: T[], seed: number): T[] {
  const a = [...arr];
  let s = seed >>> 0;
  for (let i = a.length - 1; i > 0; i--) {
    s = Math.imul(s, 1664525) + 1013904223 >>> 0;
    const j = s % (i + 1);
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ~2000 common 6-letter English words (curated answer list)
export const ANSWERS: string[] = [
  "abroad","absent","accent","access","accord","across","action","actual","advise","affect",
  "afford","afraid","agency","agenda","agreed","albeit","always","annual","anyone","anyway",
  "appeal","appear","around","aspect","assist","assume","assure","attach","attack","attain",
  "attend","august","autumn","avenue","averse","backed","barely","battle","beacon","beauty",
  "became","become","behalf","behind","beings","belief","belong","beside","beyond","bitter",
  "blacks","blanks","blazed","blight","blinks","blocks","blower","blurts","bodies","bolted",
  "border","boring","borrow","bottom","bought","bounty","branch","brands","bravely","breach",
  "bright","brings","broken","broker","bronze","browse","burden","button","buyers","called",
  "camera","cancel","cannot","canvas","carbon","career","carpet","castle","caught","caused",
  "center","chance","change","charge","choice","chosen","church","circle","cities","claims",
  "classy","client","closed","closer","clouds","combat","coming","commit","common","county",
  "course","courts","covers","create","credit","crisis","crowds","cruise","custom","cutoff",
  "damage","danger","danger","darker","deadly","deaths","debate","decide","decent","deeply",
  "defend","define","degree","delays","demand","denied","depend","design","detail","detect",
  "device","differ","direct","dollar","domain","double","drafts","dreams","driven","during",
  "easily","edited","editor","effect","either","empire","enable","energy","engage","engine",
  "enough","ensure","entire","escape","events","except","expand","expect","export","extend",
  "extend","fairly","fallen","family","famous","faster","father","faulty","fellow","female",
  "fierce","figure","filing","filter","finger","finish","flight","forces","forest","formal",
  "fossil","fought","frames","freely","fridge","friend","frozen","future","gather","gender",
  "gentle","global","golden","govern","grades","grants","growth","guests","guided","guilty",
  "handle","happen","hardly","health","hearts","height","hidden","higher","hiring","honest",
  "hoping","hosted","hotels","houses","hugely","humans","hunger","impact","income","indeed",
  "inform","inside","insist","intent","invest","island","issues","itself","joined","junior",
  "justice","keeper","killed","kings","labour","largely","launch","lawyer","leader","leaves",
  "legacy","lesson","letter","levels","lights","likely","limits","listed","little","living",
  "locked","looked","losing","lovers","lowest","mainly","manage","manner","margin","marked",
  "market","master","matter","measure","medium","merely","metals","method","middle","might",
  "mobile","moment","mostly","moving","murder","mutual","myself","narrow","nation","nature",
  "nearly","needed","nights","normal","notice","obtain","offered","office","online","opened",
  "option","orders","origin","others","output","owners","packed","parent","passed","patent",
  "paying","pencil","people","permit","phases","picked","pieces","pilots","placed","places",
  "planet","plants","played","player","plenty","policy","police","plenty","points","poorly",
  "posted","power","prefer","pretty","prison","profit","proper","proven","public","pupils",
  "purple","pushed","queens","quietly","racist","raised","random","rarely","rather","rating",
  "really","reason","recent","reduce","reform","regard","remain","remove","repeat","report",
  "rescue","result","return","review","reward","rights","rising","robust","rocket","rushed",
  "safety","sample","saying","school","screen","season","second","sector","secure","seeing",
  "sought","served","server","settle","shared","should","signal","silver","simple","simply",
  "single","sister","slight","slowly","social","solved","source","spaces","spread","stable",
  "states","status","stolen","stores","strain","street","strict","strong","struck","studio",
  "submit","sudden","suffer","summer","supply","surely","survey","switch","target","taught",
  "tested","thanks","theory","things","throne","thrown","titled","though","titles","topics",
  "totally","toward","travel","treaty","trends","trying","turned","twelve","unable","unions",
  "unique","unless","update","useful","valley","varied","verbal","victim","vision","wanted",
  "warned","weapon","weekly","weight","widely","winner","within","wonder","worker","worlds",
  "worthy","writer","yearly","yields",
];

// Larger set of valid 6-letter words (accepted for guessing, superset of ANSWERS)
// This is a representative set; in production you'd include ~10000 words
const VALID_EXTRAS: string[] = [
  "abound","absorb","abused","acidic","acting","acumen","addend","adding","admire","admits",
  "adored","adrift","adults","afield","ageing","ageism","agents","aggro","aghast","agitate",
  "agonic","ailing","airway","albeit","albums","alerts","allure","allows","almond","alpaca",
  "alpine","ambush","amends","amidst","amoral","anchor","angled","angles","ankles","anoint",
  "antics","antler","anvils","apache","apathy","aplomb","arched","ardent","argues","arises",
  "armory","arouse","arrays","arrows","artful","artist","astray","atomic","atonic","attach",
  "avoids","awoken","bailed","baking","banter","barely","barren","basalt","basics","bathed",
  "batters","beamed","beards","beaten","belted","bended","blamed","bland","bleary","blends",
  "blinks","boasts","boding","bogged","boldly","bonded","borked","botany","bouncy","brandy",
  "breach","brooch","bruise","buries","cabled","camper","candid","canine","canopy","carpet",
  "carrot","casket","casual","ceased","cement","chilly","choice","chunky","cipher","cirrus",
  "clamor","clumsy","coarse","cobalt","cobble","coiled","colony","combat","combed","compile",
  "concur","coping","corals","corous","cosmic","coughing","couple","crazed","crisps","croaks",
  "crunch","cupids","cycled","darkly","dashed","dawdle","dazzle","debris","depart","deploy",
  "deputy","desert","dimly","dinned","direly","dismal","dispel","distil","diving","docile",
  "dodged","donkey","doting","doubts","dreary","drenched","drones","drowse","drying","dubbed",
  "ducked","dumped","dusted","earthy","edging","ejects","elapse","elated","eldest","eleven",
  "elicit","eluded","eludes","elves","embers","emerge","empath","enamel","endure","enjoys",
  "enrich","entail","entwine","errant","erring","erupt","ethics","exacts","exiled","fables",
  "fading","famine","faults","fawned","feisty","fended","fervor","feudal","filmed","finest",
  "fitted","fixing","flaked","flames","flanks","flares","flashy","flavor","flawed","fleets",
  "flickr","flimsy","flinch","floods","floors","flopped","floats","flocks","folded","folly",
  "forage","forbid","forged","forges","format","fortify","forums","founds","fright","frowns",
  "frozen","fumble","fungal","gaping","garner","gilded","glassy","glazed","glints","gloomy",
  "glowed","glutes","grains","grasps","gravel","greedy","grills","grimed","grimy","gripes",
  "groans","gropes","grotesque","grouse","grudge","grumpy","gushed","gutted","hailed","handed",
  "harmed","harped","harshly","hateful","hazing","herald","heroic","hexing","hijack","hobble",
  "hooked","horrid","hosted","howled","humane","hurled","hybrid","ideals","impose","inched",
  "indent","infers","infuse","inland","inmate","innate","inputs","insane","insert","insure",
  "intact","intend","iodine","ironic","irking","isolated","jabbed","jagged","jaunty","jealous",
  "jested","jotted","jumped","jungle","kennel","kindly","kinetic","knacks","kneels","knights",
  "knobby","knotty","knowledgeable","lacked","lament","lapsed","lashed","latent","layers",
  "leaked","leaned","leaped","levied","lining","linker","lintel","listless","loosen","loping",
  "losing","lounge","lucent","lunged","lurked","malice","malign","mangle","mantle","mapped",
  "marble","marred","mashed","matted","meddle","mental","merest","merits","messes","mirror",
  "misuse","mitten","models","module","molten","mortar","mosaic","motive","mottled","mourns",
  "mutter","nagged","nasty","needle","nephews","nested","nether","neural","newborn","nimbly",
  "nobles","nimble","negate","neared","morsel","mossy","mottled","muffled","naught","nomads",
  "nuzzle","oblong","obsess","obtain","occurs","odious","omitted","opaque","orbits","outrun",
  "outset","overdo","overly","paddle","pallid","pardon","partly","patrol","peddle","pelted",
  "penned","perceive","petals","pickle","pinned","piracy","pixels","plaque","plasma","plumbs",
  "plumes","plummy","podium","polled","pooled","ponder","potent","pouted","pounds","powder",
  "preach","precise","prefers","primed","prisms","purely","pushed","putrid","puzzle","rabble",
  "radial","radish","rankly","rappel","rarest","rattle","raucous","ravine","recede","recoil",
  "reflow","refuse","relics","relies","remiss","rental","repels","rested","retool","reveal",
  "ridges","rigged","ripple","rivals","robbed","rolled","romped","rookie","rouped","rubble",
  "rugged","rumble","saddle","sallow","salute","salvage","sapped","sating","savant","scaffold",
  "scaled","scorch","sector","seethe","seldom","seized","sermon","shaken","shamed","shanty",
  "shaped","shards","sheath","shifty","shimmer","shrine","singed","sipped","sirens","skirted",
  "sloppy","slouch","snared","sneaky","snobbish","soften","somber","sorted","sprawl","sprint",
  "sputum","stamen","stared","static","steely","stench","stifle","stoked","stoned","stroll",
  "sturdy","subnet","superb","swerve","swivel","symbol","tabbed","taught","tangle","tapers",
  "tasted","tawdry","teamed","tickle","timely","tinged","tipped","tiresome","toiled","tossed",
  "treble","trifle","triples","trover","tundra","turbid","typhon","ulcers","uncanny","unfair",
  "unfit","unison","unkind","untied","untrue","upheld","upkeep","urgent","usable","vapors",
  "vexing","viable","vomits","vowing","vulgar","wafted","waging","waived","wander","washed",
  "wasted","waters","waving","weaken","wealth","welded","wicked","wisely","wished","wobble",
  "wolves","wrenched","wrestle","writhed","yelled","zoning","zoning",
];

// ─── 5-Letter Words ───────────────────────────────────────────────────────────
export const ANSWERS_5: string[] = [
  "about","above","abuse","actor","acute","admit","adopt","adult","after","again",
  "agent","agree","ahead","alarm","album","alert","alien","align","alike","alley",
  "allow","alone","along","altar","alter","angel","anger","angle","angry","anime",
  "ankle","annex","apart","apple","apply","apron","arena","argue","arise","armor",
  "array","arrow","asset","attic","audio","audit","avoid","awake","award","aware",
  "awful","badly","baker","baron","basic","basis","batch","beach","beard","beast",
  "began","begin","being","below","bench","bible","birth","black","blade","blame",
  "bland","blank","blast","blaze","bleed","blend","bless","blind","block","blood",
  "bloom","blown","blues","blunt","board","bonus","boost","booth","bound","brain",
  "brave","break","breed","brick","bride","brief","bring","broad","broke","brook",
  "brown","brush","build","built","bunch","burst","buyer","cabin","cable","candy",
  "cards","carry","catch","cause","cease","chain","chair","chaos","charm","chase",
  "cheap","check","cheek","cheer","chess","chest","chief","child","china","chips",
  "choir","chord","civil","claim","class","clean","clear","clerk","click","climb",
  "clock","clone","close","cloud","coach","coast","color","comic","comma","coral",
  "count","court","cover","craft","crash","crazy","cream","creek","crime","crisp",
  "cross","crowd","crown","cruel","crush","curve","cycle","daily","dance","death",
  "debut","decay","delay","dense","depot","depth","devil","diary","dirty","disco",
  "doubt","dough","draft","drain","drama","drank","drawn","dream","dress","drink",
  "drive","drove","drunk","dryer","dunes","dunno","dusty","eagle","early","earth",
  "eight","elite","email","empty","enemy","enjoy","enter","entry","equal","error",
  "essay","event","every","exact","exist","extra","fable","faint","faith","false",
  "fancy","fatal","fault","feast","fence","ferry","fever","fiber","field","fifth",
  "fifty","fight","final","first","fixed","flame","flash","fleet","flesh","float",
  "floor","flora","flour","flow","focus","force","forge","forth","forum","found",
  "frame","frank","fraud","fresh","front","frost","fruit","fully","funny","genre",
  "ghost","giant","given","gland","glass","globe","gloom","glory","glove","going",
  "grace","grade","grain","grand","grant","graph","grasp","grass","grave","great",
  "green","greet","grief","grill","grind","groan","gross","group","grove","grown",
  "guard","guide","guild","guile","guilt","guise","gusto","happy","harsh","haven",
  "heart","heavy","hedge","hence","herbs","honor","horse","hotel","house","human",
  "humor","hurry","hustle","ideal","image","imply","index","indie","indie","inner",
  "input","inter","intro","issue","ivory","japan","jewel","joint","joker","judge",
  "juice","juicy","kanji","karma","kayak","kneel","knife","knock","known","label",
  "lance","large","laser","later","laugh","layer","leader","learn","legal","level",
  "light","limit","liner","local","lodge","logic","loose","lover","lower","lucky",
  "lunar","magic","major","maker","manor","maple","march","match","mayor","media",
  "metal","might","minor","minus","mixed","model","money","month","moral","motel",
  "motor","mount","mouse","mouth","movie","music","myrrh","nadir","naive","naval",
  "nerve","never","night","noble","noise","north","noted","novel","nurse","occur",
  "ocean","offer","olive","omega","onset","opera","order","other","outer","owing",
  "owner","oxide","ozone","paint","panel","panic","paper","parse","party","patch",
  "pause","peace","pearl","penny","perch","phone","photo","piano","pilot","pinch",
  "pixel","pizza","place","plain","plane","plant","plate","plaza","plead","pluck",
  "plumb","plume","plush","point","polar","power","press","price","pride","prime",
  "prism","prize","proof","prose","proud","prove","psalm","pulse","punch","pupil",
  "purse","queen","query","quest","queue","quick","quiet","quota","quote","radar",
  "radio","raise","ranch","range","rapid","ratio","reach","ready","realm","rebel",
  "refer","reign","relax","reply","rider","ridge","rifle","right","risky","rival",
  "river","robot","rocky","roman","rouge","rough","round","route","royal","rugby",
  "ruler","rural","saint","salad","sauce","scale","scare","scene","scope","score",
  "scout","sense","serve","seven","shade","shake","shall","shame","shape","share",
  "sharp","shelf","shift","shine","shirt","shock","shoot","shore","short","shout",
  "shove","sight","silly","since","sixth","sixty","sized","skill","skull","slash",
  "slave","sleep","slice","slide","slope","small","smart","smell","smile","smirk",
  "smoke","snake","solar","solve","sorry","south","space","spark","spawn","speak",
  "spear","speed","spend","spent","spice","spill","spine","spite","split","spoke",
  "spoon","sport","spray","squad","stack","staff","stage","stain","stake","stale",
  "stall","stand","stark","start","state","stays","steal","steam","steel","steep",
  "steer","stern","stick","stiff","still","stock","stoic","stone","stood","store",
  "storm","story","study","style","sugar","suite","sunny","super","surge","swamp",
  "swear","sweep","sweet","swift","swirl","table","talon","taste","teach","tense",
  "tenth","their","theme","there","thick","thing","think","third","those","three",
  "threw","throw","thumb","tiger","tight","timer","tired","title","today","token",
  "total","touch","tough","towel","tower","toxic","trace","track","trade","trail",
  "train","trait","trash","treat","trend","trial","trick","troop","trout","trove",
  "truck","truly","trump","trunk","trust","truth","tuner","twice","twist","typed",
  "ultra","under","union","unity","until","upset","urban","using","usual","utter",
  "valid","value","valve","vapor","vault","verse","video","vigor","viral","virus",
  "vital","vivid","vocal","voice","voter","watch","water","weary","weave","wedge",
  "weird","where","which","white","whole","whose","wider","witch","woman","women",
  "world","wormy","worse","worst","worth","would","wound","wrath","wrist","write",
  "wrong","yacht","yield","young","youth","zebra","zoned",
];

export const VALID_EXTRAS_5: string[] = [
  "abbot","abeam","abhor","abide","abler","abode","abort","abyss","ached","aches",
  "acorn","acrid","added","adept","adore","adorn","aegis","afoot","agile","aglow",
  "aisle","algae","alibi","aloft","aloof","amass","amble","amend","amiss","ample",
  "amuse","annul","antic","anvil","aphid","apple","aptly","ardor","aroma","atone",
  "atop","avail","avert","avid","azure","bacon","bagel","banal","banjo","baste",
  "bayou","berth","beset","bevel","bliss","bloat","bloke","bloom","botch","braid",
  "brash","bravo","brawn","braze","briny","brisk","broil","brood","burly","cabal",
  "calve","carve","caste","cavil","chasm","chose","cinch","civvy","clamp","clasp",
  "cling","cloak","clomp","clout","clown","clump","cobra","cocoa","comet","comfy",
  "conch","concur","conga","copse","covet","cower","cramp","creak","credo","creep",
  "crimp","croon","crops","croup","crust","curio","cutie","daunt","debar","decal",
  "decor","decry","denim","depot","depot","derby","deter","deuce","devil","dirge",
  "ditty","divvy","dodgy","dread","dried","drill","drool","droop","drub","duvet",
  "dwarf","dwell","eclat","edify","egret","eight","eject","elude","emcee","endow",
  "ensue","envoy","ephod","etude","evade","exalt","expel","extol","exude","exult",
  "facet","farce","farce","faun","feral","fetid","fever","flair","flank","flare",
  "flask","flaunt","fledge","flies","fling","flint","flair","foamy","foray","forte",
  "frail","frond","froth","froze","frugal","gamut","gauge","gaunt","gavel","gecko",
  "gelid","giddy","gimp","girth","gizmo","gloat","gloss","glued","golem","gorge",
  "gouty","gravy","graze","grebe","grime","gripe","gruff","guano","guise","gulch",
  "gummy","guppy","gusto","gypsy","hapless","haunt","haven","heave","heist","horde",
  "humid","hyena","icily","icing","idiom","igloo","ileum","impel","inane","inept",
  "infer","ingot","inlay","inlet","inter","ionic","irate","irons","itchy","jaunt",
  "jazzy","jelly","jiffy","jiver","joust","jumbo","jumpy","junto","khaki","kiosk",
  "kitty","kluge","knave","knell","knobs","knoll","laden","lathe","lemon","lemur",
  "liege","limbo","lithe","livid","llama","loath","loopy","lowly","lucid","lurid",
  "lusty","macro","maize","manga","mango","manic","manly","masse","matey","mauve",
  "melee","melon","mercy","messy","mirth","miser","mitre","moist","moldy","money",
  "moody","mossy","motif","moxie","muddy","murky","musty","naive","nasty","natty",
  "nifty","nippy","nutty","obese","occur","offal","optic","ovoid","paddy","pagan",
  "parch","parry","patsy","paved","penal","pesky","petty","piety","pithy","plaid",
  "plait","plank","poise","poppy","potty","pouty","prank","prawn","privy","prone",
  "proxy","prude","pubic","pubis","pudgy","puffy","punky","pupal","puppy","quirky",
  "rabid","randy","rangy","ratty","rave","rayon","raspy","rebel","reedy","remix",
  "repay","repel","retro","retry","revel","rivet","rocky","rowdy","ruddy","rugby",
  "rummy","runny","rusty","rutty","sadly","saner","sassy","saucy","scald","scalp",
  "scaly","scamp","scone","scoop","scour","scram","scrub","seamy","seedy","seize",
  "semen","serum","sever","shady","shaky","shale","shave","sheaf","sheer","shewn",
  "siren","sissy","sixty","skiff","skimp","skunk","slain","slang","slant","sloth",
  "slung","slurp","smarmy","smear","snack","snaky","snare","sneer","snide","sniff",
  "snore","snort","snout","soggy","sonic","sooth","soppy","sorry","spank","spasm",
  "speck","spiel","spiky","spiral","spoof","spook","spore","spoil","spout","spry",
  "spunk","stamp","stank","stave","stead","stink","stomp","stout","strap","straw",
  "stray","strut","stuck","stung","stunk","suave","sulky","surly","swill","swine",
  "swung","taboo","tacky","taffy","tally","tangy","tardy","tarry","taunt","tawny",
  "teddy","testy","thane","thank","theft","thong","throe","timid","tipsy","titan",
  "tonal","topaz","toque","torso","total","totem","toxic","tramp","tromp","tryst",
  "tubby","tulip","tulle","tummy","tuner","tunic","turbo","twixt","typic","tyrant",
  "ulcer","undue","unfit","unify","unruly","unwed","usurp","uvula","vague","venom",
  "vicar","viper","vivid","vodka","vying","wacky","wader","waltz","warty","waspy",
  "weedy","wench","wormy","woken","wordy","wormy","wowed","yearn","zappy","zippy",
];

// ─── 7-Letter Words ───────────────────────────────────────────────────────────
export const ANSWERS_7: string[] = [
  "ability","absence","accused","achieve","acronym","adapted","address","advance",
  "affairs","against","ailment","alleged","allowed","already","altered","amazing",
  "ancient","another","anxiety","archive","arrival","artwork","assault","assumed",
  "athlete","attract","auction","auditor","average","awesome","balance","barrier",
  "beating","because","believe","between","biology","bizarre","boolean","borders",
  "bracket","breathe","brother","builder","burning","cabinet","calling","camping",
  "capital","captain","capture","carried","caution","central","century","certain",
  "chapter","charged","charity","checked","chronic","circuit","classic","climate",
  "closure","cluster","college","combine","comfort","command","comment","company",
  "compare","compete","complex","concern","concise","confirm","connect","consent",
  "consist","contact","context","control","convert","correct","counter","country",
  "courage","covered","created","creator","culture","current","customs","damaged",
  "dealing","decided","decided","decline","default","defense","defined","deliver",
  "density","despite","destroy","develop","digital","diploma","display","distant",
  "divided","diverse","driving","economy","edition","elected","element","empower",
  "engaged","engaged","enhance","enjoyed","ensured","entered","episode","examine",
  "excited","explore","exposed","extreme","factory","failure","feature","feeling",
  "fiction","filling","finance","focused","follows","foreign","forward","freedom",
  "further","gallery","general","geology","getting","glowing","granted","growing",
  "handled","harvest","healthy","helping","history","hostile","housing","however",
  "hundred","hunting","illegal","imagine","impacts","improve","include","indexed",
  "initial","inspire","install","instant","instead","integer","intense","invited",
  "January","joining","journey","justice","keeping","kitchen","landing","language",
  "largest","learned","largely","leading","leisure","limited","located","logging",
  "logical","managed","manager","mapping","marshal","measure","medical","message",
  "million","missing","mixture","monitor","morning","mounted","natural","network",
  "nominal","nothing","nuclear","nursing","obvious","offense","offered","operate",
  "optimal","organic","outside","painful","partial","patient","pattern","payment",
  "pension","percent","perfect","perform","perhaps","playing","pleased","pointer",
  "popular","portion","present","printed","problem","produce","program","protect",
  "protest","provide","publish","purpose","qualify","quarter","quickly","reached",
  "reading","realize","rebuild","receive","recover","recruit","refined","regular",
  "related","release","removed","replace","resolve","respond","restore","retired",
  "revenue","reverse","revised","rolling","roughly","running","sailing","savings",
  "science","section","secured","segment","service","shifted","similar","sitting",
  "someone","special","species","started","station","storage","strange","studied",
  "subject","success","suggest","summary","support","surface","survive","suspend",
  "through","trading","traffic","trained","turning","typical","unusual","upgrade",
  "utterly","various","venture","version","victory","viewing","violent","virtual",
  "visible","website","welfare","western","whereas","whether","without","working",
  "writing","younger","another","broader","cleaner","clearer","closely","company",
  "crucial","deliver","divided","examine","further","general","getting","hosting",
  "imaging","insular","interim","invoice","mailing","mapping","maximum","minimum",
  "notably","opening","perfect","polling","quantum","quickly","ranking","rapidly",
  "readily","recover","reports","seeking","serving","setting","showing","signing",
  "sorting","staging","storage","testing","trigger","turning","updates","uploads",
  "viewers","warning","wearing","willing","wishing","working","written","younger",
];

export const VALID_EXTRAS_7: string[] = [
  "abdomen","abolish","abridge","absolve","abstain","acclaim","acclaim","account",
  "accused","acrobat","adamant","adeptly","adjourn","admiral","adopted","advance",
  "adverse","advised","affairs","antenna","anymore","applied","arcades","arrange",
  "asunder","audible","baptism","bargain","bastion","bearing","bedrock","bedroom",
  "bemused","besides","bestow","between","blanket","bloated","blossom","blunder",
  "bolster","bowling","boycott","branded","brewing","broadly","bravely","calcium",
  "charade","charged","coastal","cobbled","cognate","cohorts","conceal","concede",
  "condemn","confine","conform","console","contain","contend","contest","convene",
  "counsel","crazily","darkened","dazzled","decades","devoted","dialect","discord",
  "dismiss","display","dormant","dropped","earthen","earnest","elapsed","emerged",
  "empathy","enclave","enforce","enlarge","enqueue","entered","evident","evolved",
  "exclaim","exhaust","extract","fertile","fervent","fiction","fighter","filling",
  "fixture","founded","fragile","frantic","frigate","furtive","gridlock","grossly",
  "hamster","handout","happens","hardest","harness","hastily","heartfelt","heavier",
  "heavily","highway","hostile","humming","hypothetically","illegal","implicit",
  "imposed","incline","ingrain","inhabit","inherit","inspect","intense","intrude",
  "invalid","invoice","isolate","journal","kingdom","kinship","lacking","lampoon",
  "landing","largely","layered","layoffs","lecture","letting","liberals","lighter",
  "linking","lengthy","literal","logging","looming","lovable","lowland","loyalty",
  "mandate","marking","mapping","matured","maximum","minimum","mopping","mourning",
  "mutated","mystery","nominal","notable","obscure","onboard","ongoing","overall",
  "overlap","oversee","porting","powered","precede","program","profile","profuse",
  "projecting","protest","rampage","ranking","rapidly","ratify","reached","readily",
  "rebuild","refined","refresh","require","resolve","resumed","revised","routing",
  "scaling","scoring","secured","seeming","sensing","sketchy","slowing","smaller",
  "solving","spacing","started","startle","stopped","storing","stretch","suggest",
  "surging","suspend","tablets","tantrum","theorem","therapy","thrifty","tighten",
  "transit","trouble","tumbled","uncover","undergo","uniform","unravel","untamed",
  "unusual","upended","uptight","villain","vaccine","varsity","vastly","verbose",
  "vibrant","wartime","wealthy","weighted","welding","whereas","whimper","worsened",
];

// ─── Unified valid word sets ──────────────────────────────────────────────────
export const VALID_WORDS: Set<string> = new Set([...ANSWERS, ...VALID_EXTRAS]);
export const VALID_WORDS_5: Set<string> = new Set([...ANSWERS_5, ...VALID_EXTRAS_5]);
export const VALID_WORDS_7: Set<string> = new Set([...ANSWERS_7, ...VALID_EXTRAS_7]);

// Pre-shuffled answer lists (computed once at module load)
const ANSWERS_SHUFFLED   = seededShuffle(ANSWERS,   0xc0ffee06);
const ANSWERS_5_SHUFFLED = seededShuffle(ANSWERS_5, 0xc0ffee05);
const ANSWERS_7_SHUFFLED = seededShuffle(ANSWERS_7, 0xc0ffee07);

export function getDailyAnswer(wordLength = 6): string {
  const day = getDayNumber();
  const answers = wordLength === 5 ? ANSWERS_5_SHUFFLED
                : wordLength === 7 ? ANSWERS_7_SHUFFLED
                : ANSWERS_SHUFFLED;
  return answers[((day - 1) % answers.length + answers.length) % answers.length];
}
